# This file configures the hello-world app which serves public web traffic.
apiVersion: apps/v1
kind: Deployment
metadata:
  name: body-mass-index-sml
spec:
  replicas: 1
  selector:
    matchLabels:
      app: bmi
  template:
    metadata:
      labels:
        app: bmi
    spec:
      containers:
      - name: body-mass-index
        # Replace $GCLOUD_PROJECT with your project ID
        image: gcr.io/advance-medium-316412/body-mass-index:latest
        # This app listens on port 5000 for web traffic by default.
        ports:
        - containerPort: 5000
        env:
          - name: PORT
            value: "5000"